### ISSUE TITLE
Flatpaks are not backed up

### ISSUE THREAD

**Issue by GammaGames** [teejee2008/aptik-plus#6]
Running `flatpak list` shows a list of packages installed:

![image](https://user-images.githubusercontent.com/7832163/68712799-b5e2f680-0559-11ea-9e07-2f3cd894304a.png)

Running `aptik --list-flatpaks` has no output:

![image](https://user-images.githubusercontent.com/7832163/68712812-bbd8d780-0559-11ea-8668-2d60c04fb561.png)

**Comment by GammaGames** [comment]
@teejee2008 I understand that it's the end of the year and you're likely busy, but is there any update on this?

**Comment by teejee2008** [comment]
This will be fixed in the next update (available this weekend).

Sorry for the delayed response. Please send me an email for any future issues. It's easier for me to respond by email.

**Comment by teejee2008** [comment]
What Linux distribution are you using? The output of `flatpak list` is very different on your system.

**Comment by teejee2008** [comment]
Send me the output of following commands:
```
flatpak --version
flatpak list -d --system
```

**Comment by teejee2008** [comment]
Fixed in v19.12. Please update.
```
sudo apt update
sudo apt install aptik*
```

**Comment by GammaGames** [comment]
`flatpak list -d --system` and `aptik --list-flatpaks` still don't print anything, I'm on `Flatpak 1.4.3` and aptik `19.12`.

`flatpak list -d --user` does print out my installed packages, though. It looks like they're all listed in user now.
![image](https://user-images.githubusercontent.com/7832163/70922511-72116000-1fe3-11ea-99f1-e04a8d84f2e9.png)

I'm on elementary OS 5.1, which is built on Ubuntu 18.04.3 LTS.

**Comment by teejee2008** [comment]
Flatpaks installed in "user" mode are located in your home directory
`~/.local/share/flatpak/`

These will get backed-up and restored along with other data in your home directory (section "Home Data").

**Comment by GammaGames** [comment]
What if I decide that I'm not going to back up my entire home directory and I just want to backup my documents ,pictures, etc?

**Comment by teejee2008** [comment]
The "Home Data" section includes everything in home directory by default. You have to manually go and exclude any file or folder that you don't need.

If you exclude things from backup without understanding what they contain, then needless to say - those things will not be backed up. Don't change the defaults unless you know what you are doing.

I'll add a warning message in the next version that will pop-up when someone tries to exclude ~/.local ~/.config etc
